### ISSUE TITLE
Connect to Meetup API and display events

### ISSUE THREAD

**Issue by hbrysiewicz** [sandiegojs/sandiegojs-api#1]
Create a middleware for [Meetup API integration]([Meetup API documentation](https://www.meetup.com/meetup_api/docs/). Response should be provided in [JSONAPI](http://jsonapi.org) format.
## Subtasks
- [x] Create route `api/v1/events`
- [x] Create Meetup module
- [x] Create Meetup module action to retrieve events
- [x] Create controller `api/v1/events` that implements Meetup module
- [ ] Serialize response from Meetup to [JSONAPI spec](http://jsonapi.org)
- [ ] Testing!
## Resources

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs ember appi](http://github.com/sandiegojs/sandiegojs)

**Comment by marksiemers** [comment]
Should it be more flexible or "event provider" agnostic? Handling both meetup and EventBrite? Or at least architected in a way to use meetup, but also with the ability to plug in new providers?

**Comment by hbrysiewicz** [comment]
@marksiemers it's just an http request and this is just middleware, I don't see the need to over-architect it. I'm open to seeing a PR if you had something in mind though.

The request endpoints for both services "event" listings would be different and the responses would also be different. 

TODO still is to write a serializer that takes the Meetup API response and converts it to a proper [JSONAPI format](http://jsonapi.org)
