### ISSUE TITLE
Blog posts - first pass

### ISSUE THREAD

**Issue by hbrysiewicz** [sandiegojs/sandiegojs-api#6]
For a first pass, basic CRUD for blog posts. Users should be authenticated so blocked by #5. For a first pass this should be limited to white-listed users (admins).

Open for conversation - should we just leverage an existing blogging platform and API rather than rolling our own?
## Subtasks
- [ ] `BlogPost` model
- [ ] `POST` for `/posts` will create a new `BlogPost`
- [ ] `GET` for `/posts` will return all `BlogPost` in order of most recent, un-archived only
- [ ] `PUT` for `/posts/:id` will update a `BlogPost` that already exists
- [ ] `DELETE` for `/posts/:id` will archive a `BlogPost` that already exists
- [ ] Attribute validation for `POST` and `PUT` actions
- [ ] Testing
## Blog Post Model
- crud timestamps
- title
- author relationship
- body (markdown)
- header image (like on medium)
## Resources

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs ember appi](http://github.com/sandiegojs/sandiegojs)
