### ISSUE TITLE
Job board

### ISSUE THREAD

**Issue by hbrysiewicz** [sandiegojs/sandiegojs-api#7]
Once users are logged in they should have the ability to create a job posting with an expiration no greater than 30 days. These will be flagged as pending and will require an admin to approve. 

Since this requires Authentication, it is blocked by #5 
## Subtasks
- [ ] `JobPost` model
- [ ] `POST` for `/job-posts` will create a new `JobPost`
- [ ] `GET` for `/job-posts` will return all approved, non-archived `JobPost` in order of most recent
- [ ] `PUT` for `/job-posts/:id` will update existing `JobPost`
- [ ] `DELETE` for `/job-posts/:id` will archive existing `JobPost`
- [ ] Action to handle approval - `POST` to `/job-posts/:id/approve`
- [ ] Attribute validation on `POST` and `PUT`
- [ ] Testing
## Resources

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs ember appi](http://github.com/sandiegojs/sandiegojs)
