### ISSUE TITLE
Youtube middleware

### ISSUE THREAD

**Issue by hbrysiewicz** [sandiegojs/sandiegojs-api#9]
Much like the Meetup integration, let's hookup to the [sandiegojs channel on youtube](youtube.com/sandiegojs) so that users can view the available videos and see most recent.
## Subtasks
- [ ] `GET` `api/v1/videos` action
- [ ] YouTube module to retrieve videos - middleware
- [ ] Serialize response to [JSONAPI spec](http://jsonapi.org)
- [ ] Testing!
## Resources

[Join our Slack](http://sandiegojs.herokuapp.com/) and join the `#sdjs-website` channel
Checkout the [sandiegojs ember appi](http://github.com/sandiegojs/sandiegojs)
